numero1 = int (input("Digite um número inteiro: "))
numero2 = int (input("Digite um outro número interio: "))
soma = (numero1 + numero2)
produto = (numero1 + numero2)
print(f"A soma dos números citados à cima tem o valor de:{soma}"f" O produto dos números:{produto}")